# Generated by Django 2.0.6 on 2018-06-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180607_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='destination',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
