# Generated by Django 2.0.6 on 2018-06-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='adventure',
            field=models.BooleanField(default=False),
        ),
    ]
